spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/joke_db
    username: postgres
    password: Snatch_My-Data-Please69))
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true